udpdates

diff --git a/.github/workflows/build_and_run.yml b/.github/workflows/build_and_run.yml
--- a/.github/workflows/build_and_run.yml
+++ b/.github/workflows/build_and_run.yml
@@ -76,6 +76,17 @@ jobs:
           timeout 10 rostopic list
         continue-on-error: true
 
+      - name: Check if topics exist
+        run: |
+          source /opt/ros/${{ matrix.rosdistro }}/setup.sh
+          source $GITHUB_WORKSPACE/catkin_ws/devel/setup.bash
+          rosrun integration_tests check_topics.py
+          # test failed if there is an rospy logerror
+          if [ $? -ne 0 ]; then
+            exit 1
+          fi
+        continue-on-error: true
+
       - name: Evaluate test result
         run: |
           source /opt/ros/${{ matrix.rosdistro }}/setup.sh
