Update build_and_run.yml

diff --git a/.github/workflows/build_and_run.yml b/.github/workflows/build_and_run.yml
--- a/.github/workflows/build_and_run.yml
+++ b/.github/workflows/build_and_run.yml
@@ -44,16 +44,29 @@ jobs:
         
     - name: Start Gazebo headless
       run: |
+        set -x
         echo "Starting Xvfb..."
         Xvfb :99 -screen 0 1920x1080x16 &
         sleep 5
         echo "Sourcing setup.bash..."
         source devel/setup.bash
         echo "Launching Gazebo..."
-        roslaunch match_gazebo big_square.launch gui:=false &
+        roslaunch match_gazebo big_square.launch gui:=false
         sleep 30
         echo "Gazebo launch completed."
       shell: bash
+
+    - name: Check for roslaunch errors
+      run: |
+        if [ $? -ne 0 ]; then
+          echo "roslaunch failed"
+          exit 1
+        fi
+      shell: bash
+
+    - name: Check Gazebo installation
+      run: gazebo --version
+
 
 
     - name: Check if robot spawns
